---
title: "Resume"
---
------


### **EDUCATION**
#### **Columbia University Mailman School of Public Health**	- *New York, NY - May 2023*

**Master of Public Health (MPH)**, Epidemiology, Certificate of Health Policy and Practice, GPA: 4.10

* *Relevant Courses*: Health Economics, Application of Epidemiologic Research Methods, Design and Conduct of Observational Epidemiology, Analysis of Categorical Data, Healthcare Accounting & Budgeting, Data Science

#### **Johns Hopkins University**	- *Baltimore, MD, -	            May 2021*

**Bachelor of Science**, Double-major: Molecular and Cellular Biology, Sociology, GPA: 3.91, Dean’s List 

#### **The University of Oxford, Study Abroad** 			         - *Oxford, United Kingdom 	           -  Sep 2019 – June 2020*
Biochemistry course, coupled with independent literature review research focused on cancer development through chronic bacterial infection 

------


### **RELEVANT EXPERIENCE**

#### **Médecins Sans Frontières/Doctors Without Borders** 	- *Remote	          -  Summer 2022*
##### *Summer Data Analyst, Brazil Medical Unit*

•	Conducted literature reviews and designed survey questions to analyze the nexus between climate change and migrant health in Central and South America

•	Conducted data analysis and cleaning for a dataset of +500 records using SAS and Excel to identify barriers to health and migration trajectories of migrants in Central and South America

•	Communicated findings through written reports and data visualization of survey data using SAS and Excel to MSF team and stakeholders 	

##### **Johns Hopkins University** - 	*Baltimore, MD	    -    Sep 2018 – May 2021*
##### *Research Assistant, Oncology Department – Dr. Cynthia Sears (Sep 2020 – May 2021)*

•	Organized and analyzed metagenomics database of more than 400 samples to identify potential bacterial genes of interest in the human gut microbiome that may pose as possible functional biomarkers for colorectal cancer and presented findings in a weekly report to research team

##### *Research Assistant, Sociology Department – Dr. Alexandre White (Spring 2020)*

•	Streamlined over 100 population and demographics data sets for the Hopkins Population Centre Data Hub used for epidemiological and medical research of COVID-19 to provide evidence-based policy recommendations
Research Assistant, Immunology Department – Dr. Andrea Cox (Sep 2018 – May 2019)

•	Conducted over 100 mouse DNA extractions from blood and tissue samples to assess the presence of HSV DNA and understand the effects of LRRK2 protein mutation in inflammasome activity

•	Conducted a site-directed mutagenesis for plasmid insertion independently and in coordination with primary investigator to understand the effects of LRRK2 protein mutation in Crohn’s disease development

#### **NISI**  - 	*Hong Kong, China	                   -                 Summer 2019*
##### *Summer Intern, Clinical Affairs Department* 

•	Researched and presented trending and available bariatric and metabolic surgeries, as well as the clinical trial landscape in India, China, and Australia, to supplement the development of NISI’s minimally invasive endoscopic surgical robot

•	Analyzed 30+ colonoscopy recordings to assist in developing an artificial intelligence program aimed at complimenting endoscopic surgical procedures

#### **The University of Hong Kong** - 	*Hong Kong, China	                 -                   Summer 2018*
##### *Summer Intern, Microbiology Department – Dr. Jasper Chan*

•	Collaborated with others in the lab and conducted over 50 plaque assays and TCID50 tests on RNA viruses to determine the efficacies of multiple drugs 

------


### **LEADERSHIP & VOLUNTEER EXPERIENCE**

#### **Columbia University Mailman School of Public Health** - 	*New York, NY	  -   Fall 2022*
##### *Teaching Assistant - Integration of Science and Practice; Personal Leadership in Public Health*

•	Mentored 25 graduate students in applying public health knowledge to real world case studies and in developing personal leadership skills 

#### **Engineers Without Borders** - 	*Baltimore, MD	          -             Sep 2017 – May 2021*
##### *Mentor*

•	Spearheaded organizational meetings and developed science-based experiments for local middle-school children to promote and foster their interest in the scientific field 

------


### **SKILLS**

**Data Analysis**: R, STATA, SAS (All Intermediate) | Python (Beginner) 

**Research**: Strong research skills and familiarity with various academic databases including PubMed

**Lab**: Substantial experience within a wet lab environment and comfortable with numerous laboratory skills

**Computer**: Excel (Advanced) Adobe Photoshop (Intermediate)

